# Stage 4 scoring — lecanemab_WT (WT) co-fold vs Aβ1-16. Same settings as WT Stage 2.2.
version: 1
sequences:
  - protein:
      id: H
      sequence: EVQLVESGGGLVQPGGSLRLSCSASGFTFSSFGMHWVRQAPGKGLEWVAYISSGSSTIYYGDTVKGRFTISRDNAKNSLFLQMSSLRAEDTAVYYCAREGGYYYGRSYYTMDYWGQGTTVTVSS
      msa: empty
  - protein:
      id: L
      sequence: DVVMTQSPLSLPVTPGAPASISCRSSQSIVHSNGNTYLEWYLQKPGQSPKLLIYKVSNRFSGVPDRFSGSGSGTDFTLRISRVEAEDVGIYYCFQGSHVPPTFGPGTKLEIK
      msa: empty
  - protein:
      id: P
      sequence: DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIA
      msa: empty
