#!/usr/bin/env python
"""Stage 1 — ANARCI-number the lecanemab Fv (IMGT/Kabat/Chothia) and annotate
CDRs (IMGT definition) + Vernier-zone positions (Kabat, Foote & Winter 1992).

Inputs : data/raw/lecanemab_fv.fasta  (VH, VL)
Outputs: data/interim/fv_numbering/{chain}_{scheme}.tsv  (per-residue numbering)
         data/interim/fv_numbering/cdr_vernier_map.md     (human-readable map)
Usage  : conda run -n lecam python scripts/stage1_inputs/number_fv.py
"""
from __future__ import annotations
import os, sys
from Bio import SeqIO
from anarci import number

REPO = "/global/project/hpcg6049/lecanemab-am"
FASTA = f"{REPO}/data/raw/lecanemab_fv.fasta"
OUT = f"{REPO}/data/interim/fv_numbering"
SCHEMES = ["imgt", "kabat", "chothia"]

# IMGT CDR position ranges (inclusive) — scheme-independent IMGT definition.
IMGT_CDR = {"CDR1": (27, 38), "CDR2": (56, 65), "CDR3": (105, 117)}

# Vernier-zone residues, Kabat numbering (Foote & Winter, J Mol Biol 1992; a
# reference set — exact membership varies slightly across sources).
VERNIER_KABAT = {
    "H": [2, 27, 28, 29, 30, 47, 48, 49, 67, 69, 71, 73, 78, 93, 94],
    "L": [2, 4, 35, 36, 46, 47, 48, 49, 64, 66, 68, 69, 71],
}


def load_fv():
    recs = list(SeqIO.parse(FASTA, "fasta"))
    out = {}
    for r in recs:
        cid = r.id.lower()
        if "vh" in cid:
            out["VH"] = str(r.seq)
        elif "vl" in cid:
            out["VL"] = str(r.seq)
    if "VH" not in out or "VL" not in out:
        sys.exit(f"ERROR: need VH and VL in {FASTA}; got {[r.id for r in recs]}")
    return out


def number_chain(seq, scheme):
    numb, ctype = number(seq, scheme=scheme, allow={"H", "K", "L"})
    if not numb:
        sys.exit(f"ERROR: ANARCI failed to number sequence under {scheme}")
    # normalise kappa/lambda to 'L' for Vernier lookup
    cls = "H" if ctype == "H" else "L"
    return numb, ctype, cls


def cdrs_imgt(seq):
    """Return {CDRname: (seq, 'start-end')} using IMGT numbering."""
    numb, ctype, _ = number_chain(seq, "imgt")
    res = {}
    for name, (lo, hi) in IMGT_CDR.items():
        aas, poss = [], []
        for (pos, ins), aa in numb:
            if lo <= pos <= hi and aa != "-":
                aas.append(aa)
                poss.append(f"{pos}{ins}".strip())
        res[name] = ("".join(aas), f"{poss[0]}-{poss[-1]}" if poss else "-")
    return res, ctype


def vernier(seq, cls):
    """Residues at Kabat Vernier positions."""
    numb, ctype, _ = number_chain(seq, "kabat")
    want = set(VERNIER_KABAT[cls])
    out = []
    for (pos, ins), aa in numb:
        if pos in want and aa != "-" and ins == " ":
            out.append((pos, aa))
    return out


def write_numbering(chain, seq):
    for sch in SCHEMES:
        numb, ctype, _ = number_chain(seq, sch)
        path = f"{OUT}/{chain}_{sch}.tsv"
        with open(path, "w") as fh:
            fh.write("kabat_imgt_pos\tins\taa\n")
            for (pos, ins), aa in numb:
                if aa != "-":
                    fh.write(f"{pos}\t{ins.strip()}\t{aa}\n")
    return ctype


def main():
    os.makedirs(OUT, exist_ok=True)
    fv = load_fv()
    lines = ["# Lecanemab Fv — ANARCI numbering, CDRs (IMGT) & Vernier (Kabat)",
             "", "Generated by `scripts/stage1_inputs/number_fv.py`.",
             "Schemes: IMGT, Kabat, Chothia (per-residue TSVs in this dir).", ""]
    for chain in ("VH", "VL"):
        seq = fv[chain]
        ctype = write_numbering(chain, seq)
        cdr, _ = cdrs_imgt(seq)
        cls = "H" if chain == "VH" else "L"
        vz = vernier(seq, cls)
        lines += [f"## {chain}  (len {len(seq)}, ANARCI chain type {ctype})", "",
                  "**CDRs (IMGT definition):**", ""]
        for name in ("CDR1", "CDR2", "CDR3"):
            s, rng = cdr[name]
            lines.append(f"- {name}  [{rng}]  `{s}`")
        lines += ["", "**Vernier-zone residues (Kabat numbering, Foote & Winter 1992):**",
                  "", "  " + ", ".join(f"{p}{aa}" for p, aa in vz), ""]
        print(f"{chain}: type={ctype}  CDR1={cdr['CDR1'][0]} CDR2={cdr['CDR2'][0]} CDR3={cdr['CDR3'][0]}  vernier_n={len(vz)}")
    with open(f"{OUT}/cdr_vernier_map.md", "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}/cdr_vernier_map.md + per-scheme TSVs")


if __name__ == "__main__":
    main()
